# Generated by Django 3.0.5 on 2021-07-06 17:28

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='tracks',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Track'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tracks',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='main.Track'),
        ),
    ]
